### ISSUE TITLE
install fail; etcd3-0.11.1; ValueError: need more than 0 values to unpack

### ISSUE THREAD

**Issue by DevenWen** [kragniz/python-etcd3#1803]
hi, thanks for the great lib you made! But I got an error when I ininstall etcd3 by pip.

env:
OS: ubuntu 16.4
pip version: 9.0.3
python version: 2.7.12

I build a docker image for python project, and I need to install python deps first.
docker file script:
```

RUN pip install -i https://pypi.douban.com/simple --upgrade pip==9.0.3 \
    && pip install -i https://pypi.douban.com/simple \
        APScheduler==3.0.6 \
        Beaker==1.6.4 \
        Cython==0.20.1 \
        Jinja2==2.9.5 \
        Pillow==4.0.0 \
        SQLAlchemy==0.9.4 \
        WebOb==1.4 \
        blinker==1.3 \
        bottle==0.12.7 \
        celery==3.1.18 \
        cssmin==0.2.0 \
        etcd3==0.11.1 \   # fail!!!
        gitdb2==2.0.6 \
        gitpython==2.1.0\
        hiredis==0.2.0 \
        jsmin==2.1.0 \
        jsonschema==2.3.0 \
        mongoengine==0.16.1 \
        monthdelta==1.0b0 \
        openpyxl==1.6.1\
        pandas==0.19.2 \
        pika==0.10.0 \
        ply==3.10 \
        pycrypto==2.6 \
        pymongo==3.7.2 \
        pytz==2014.3 \
        pyyaml==3.12\
        qrcode==5.1 \
        redis==2.10.5 \
        rpy2==2.8.5 \
        simplejson==2.3.2 \
        uWSGI==2.0.18 \
        webassets==0.10.1 \
        requests==2.20.0 \
    && rm -rf ~/.cache
```

as result, I got an error as follow.
```
Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-gSWR7x/etcd3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpwdYFXWpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/etcd3
  copying etcd3/__init__.py -> build/lib.linux-x86_64-2.7/etcd3
  copying etcd3/utils.py -> build/lib.linux-x86_64-2.7/etcd3
  copying etcd3/locks.py -> build/lib.linux-x86_64-2.7/etcd3
  copying etcd3/events.py -> build/lib.linux-x86_64-2.7/etcd3
  copying etcd3/client.py -> build/lib.linux-x86_64-2.7/etcd3
  copying etcd3/transactions.py -> build/lib.linux-x86_64-2.7/etcd3
  copying etcd3/leases.py -> build/lib.linux-x86_64-2.7/etcd3
  copying etcd3/exceptions.py -> build/lib.linux-x86_64-2.7/etcd3
  copying etcd3/watch.py -> build/lib.linux-x86_64-2.7/etcd3
  copying etcd3/members.py -> build/lib.linux-x86_64-2.7/etcd3
  creating build/lib.linux-x86_64-2.7/etcd3/etcdrpc
  copying etcd3/etcdrpc/__init__.py -> build/lib.linux-x86_64-2.7/etcd3/etcdrpc
  copying etcd3/etcdrpc/rpc_pb2_grpc.py -> build/lib.linux-x86_64-2.7/etcd3/etcdrpc
  copying etcd3/etcdrpc/auth_pb2.py -> build/lib.linux-x86_64-2.7/etcd3/etcdrpc
  copying etcd3/etcdrpc/rpc_pb2.py -> build/lib.linux-x86_64-2.7/etcd3/etcdrpc
  copying etcd3/etcdrpc/kv_pb2.py -> build/lib.linux-x86_64-2.7/etcd3/etcdrpc
  running egg_info
  writing requirements to etcd3.egg-info/requires.txt
  writing etcd3.egg-info/PKG-INFO
  writing top-level names to etcd3.egg-info/top_level.txt
  writing dependency_links to etcd3.egg-info/dependency_links.txt
  warning: manifest_maker: standard file '-c' not found

  reading manifest file 'etcd3.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '__pycache__' found under directory '*'
  warning: no previously-included files matching '*.py[co]' found under directory '*'
  warning: no files found matching '*.jpg' under directory 'docs'
  warning: no files found matching '*.png' under directory 'docs'
  warning: no files found matching '*.gif' under directory 'docs'
  writing manifest file 'etcd3.egg-info/SOURCES.txt'
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/etcd3
  copying build/lib.linux-x86_64-2.7/etcd3/__init__.py -> build/bdist.linux-x86_64/wheel/etcd3
  copying build/lib.linux-x86_64-2.7/etcd3/utils.py -> build/bdist.linux-x86_64/wheel/etcd3
  copying build/lib.linux-x86_64-2.7/etcd3/locks.py -> build/bdist.linux-x86_64/wheel/etcd3
  copying build/lib.linux-x86_64-2.7/etcd3/events.py -> build/bdist.linux-x86_64/wheel/etcd3
  copying build/lib.linux-x86_64-2.7/etcd3/client.py -> build/bdist.linux-x86_64/wheel/etcd3
  copying build/lib.linux-x86_64-2.7/etcd3/transactions.py -> build/bdist.linux-x86_64/wheel/etcd3
  copying build/lib.linux-x86_64-2.7/etcd3/leases.py -> build/bdist.linux-x86_64/wheel/etcd3
  copying build/lib.linux-x86_64-2.7/etcd3/exceptions.py -> build/bdist.linux-x86_64/wheel/etcd3
  creating build/bdist.linux-x86_64/wheel/etcd3/etcdrpc
  copying build/lib.linux-x86_64-2.7/etcd3/etcdrpc/__init__.py -> build/bdist.linux-x86_64/wheel/etcd3/etcdrpc
  copying build/lib.linux-x86_64-2.7/etcd3/etcdrpc/rpc_pb2_grpc.py -> build/bdist.linux-x86_64/wheel/etcd3/etcdrpc
  copying build/lib.linux-x86_64-2.7/etcd3/etcdrpc/auth_pb2.py -> build/bdist.linux-x86_64/wheel/etcd3/etcdrpc
  copying build/lib.linux-x86_64-2.7/etcd3/etcdrpc/rpc_pb2.py -> build/bdist.linux-x86_64/wheel/etcd3/etcdrpc
  copying build/lib.linux-x86_64-2.7/etcd3/etcdrpc/kv_pb2.py -> build/bdist.linux-x86_64/wheel/etcd3/etcdrpc
  copying build/lib.linux-x86_64-2.7/etcd3/watch.py -> build/bdist.linux-x86_64/wheel/etcd3
  copying build/lib.linux-x86_64-2.7/etcd3/members.py -> build/bdist.linux-x86_64/wheel/etcd3
  running install_egg_info
  Copying etcd3.egg-info to build/bdist.linux-x86_64/wheel/etcd3-0.11.1.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-gSWR7x/etcd3/setup.py", line 60, in <module>
      tests_require=test_requirements
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 232, in run
      self.distinfo_dir)
    File "/usr/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 399, in egg2dist
      distribution=self.distribution)
    File "/usr/lib/python2.7/dist-packages/wheel/metadata.py", line 176, in pkginfo_to_dict
      new_requirements = sorted(convert_requirements(requirements))
    File "/usr/lib/python2.7/dist-packages/wheel/metadata.py", line 231, in convert_requirements
      parsed_requirement = pkg_resources.Requirement.parse(req)
    File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2833, in parse
      req, = parse_requirements(s)
  ValueError: need more than 0 values to unpack

  ----------------------------------------
  Failed building wheel for etcd3
  Running setup.py clean for etcd3
```

any comment will be appreciated!

**Comment by DevenWen** [comment]
I figout myself, for update wheel version.
