### ISSUE TITLE
a problem in using lease

### ISSUE THREAD

**Issue by qshzhang** [kragniz/python-etcd3#1838]
```
etcd = etcd3.client(host="localhost", port=2379)
lease = etcd.lease(20)
etcd.put('/map/metric/smart/third', 'db-5', lease=lease)
```
some problems are encountered,
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/etcd3-0.12.0-py3.6.egg/etcd3/client.py", line 48, in handler
    _translate_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/etcd3-0.12.0-py3.6.egg/etcd3/client.py", line 46, in handler
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/etcd3-0.12.0-py3.6.egg/etcd3/client.py", line 424, in put
    metadata=self.metadata
  File "/usr/local/lib64/python3.6/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib64/python3.6/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.NOT_FOUND
        details = "etcdserver: requested lease not found"
        debug_error_string = "{"created":"@1648176478.266425881","description":"Error received from peer ipv6:[::1]:2379","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"etcdserver: requested lease not found","grpc_status":5}"

**Comment by qshzhang** [comment]
the reason is that the time is expired
