### ISSUE TITLE
Bug in grpcio>=1.54.0

### ISSUE THREAD

**Issue by bashar94** [kragniz/python-etcd3#2212]
I am getting the following error when I tried to authenticate using username and password. 

_**Though using grpcio==1.44.0 solved the issue for now**_

Just created this issue so that others can get an idea about the solutions and this issue gets fixed in upcoming versions.

My etcd database version is 3.5.9 and etcd3==0.12.0 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/myproject/venv/lib/python3.10/site-packages/etcd3/client.py", line 48, in handler
    _translate_exception(exc)
  File "/root/myproject/venv/lib/python3.10/site-packages/etcd3/client.py", line 46, in handler
    return f(*args, **kwargs)
  File "/root/myproject/venv/lib/python3.10/site-packages/etcd3/client.py", line 534, in status
    status_response = self.maintenancestub.Status(
  File "/root/myproject/venv/lib/python3.10/site-packages/grpc/_channel.py", line 1030, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/root/myproject/venv/lib/python3.10/site-packages/grpc/_channel.py", line 910, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAUTHENTICATED
	details = "Established channel does not have a sufficient security level to transfer call credential."
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Established channel does not have a sufficient security level to transfer call credential.", grpc_status:16, created_time:"2023-06-25T10:18:55.858860189+00:00"}"
```

**Comment by nntp4** [comment]
@bashar94 I used `etcd3 = "0.12.0"` and ` grpcio = "1.44.0"` with poetry in my project. 
![image](https://github.com/kragniz/python-etcd3/assets/90622470/99da2835-6252-4f29-bda3-b8b4520b2470)

But a segfault occurs, have you run into this problem? 
![image](https://github.com/kragniz/python-etcd3/assets/90622470/481c9e0d-1422-4019-930b-765a9bfe0375)
