### ISSUE TITLE
What is the API to get all the keys (not values) in etcd3?

### ISSUE THREAD

**Issue by vhosakot** [kragniz/python-etcd3#362]
The `get_all()` API returns the values of all the keys, but not the keys themselves.

After putting the following keys and values, what is the API to get a list of just the keys `/foo`, `/bar`, `/baz` and `/qux`?

```
>>> etcd.put("/foo", "a")
>>> etcd.put("/bar", "b")
>>> etcd.put("/baz", "c")
>>> etcd.put("/qux", "d")
```

I was not able to find this in the documentation in https://python-etcd3.readthedocs.io/en/latest/usage.html.

It is possible to get just the keys in `etcd3` using `etcdctl` the following way:

```
ETCDCTL_API=3 etcdctl get --prefix=true "" | grep '/'
/bar
/baz
/foo
/qux
```

But, I wasn't able to find the python API to do the above. Let me know if I'm missing anything.

**Comment by graysonchao** [comment]
Looks like it is `get_all`: https://python-etcd3.readthedocs.io/en/latest/usage.html#etcd3.Etcd3Client.get_all

**Comment by kragniz** [comment]
There isn't a method to do this, but you can get all and extract only the keys:

```python
>>> c = etcd3.client()
>>> [m.key for (_, m) in c.get_all()]
[b'/bar', b'/baz', b'/foo', b'/qux'] 
```

**Comment by kragniz** [comment]
Maybe a utility function for this would be useful, if you'd like to submit a pr

**Comment by vhosakot** [comment]
Thanks @kragniz, that works!

```
>>> etcd.put("/foo", "a")
>>> etcd.put("/bar", "b")
>>> etcd.put("/baz", "c")
>>> etcd.put("/qux", "d")

>>> [m.key for (_, m) in etcd.get_all()]
['/bar', '/baz', '/foo', '/qux']

>>> for (_,m) in etcd.get_all():
...     print m.key
... 
/bar
/baz
/foo
/qux
```

**Comment by amir-amf** [comment]
Not a good method in production environment when you have tons of keys and values!
I think they should implement the alternative for 
etcdctl get "KEY" --prefix --keys-only

**Comment by grandamp** [comment]
Howdy,

Is there any appetite to include a parameter for `get_all` or `get_prefix` to only obtain the keys?

Similar to:

`etcdctl --endpoints=localhost:2379 get /some/prefix/ --prefix --keys-only`

This solution works where the overall number of keys and data does not exceed the GRPC limit of 4mb.

I.e.,

```TEXT
$ python3
Python 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import etcd3
>>> etcd = etcd3.client(host='localhost', port=2379)
>>> [m.key for (_, m) in etcd.get_all()]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
  File "/home/tejohnson/.local/lib/python3.10/site-packages/etcd3/client.py", line 382, in get_all
    range_response = self.get_all_response(**kwargs)
  File "/home/tejohnson/.local/lib/python3.10/site-packages/etcd3/client.py", line 48, in handler
    _translate_exception(exc)
  File "/home/tejohnson/.local/lib/python3.10/site-packages/etcd3/client.py", line 46, in handler
    return f(*args, **kwargs)
  File "/home/tejohnson/.local/lib/python3.10/site-packages/etcd3/client.py", line 368, in get_all_response
    return self.kvstub.Range(
  File "/home/tejohnson/.local/lib/python3.10/site-packages/grpc/_channel.py", line 1181, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/tejohnson/.local/lib/python3.10/site-packages/grpc/_channel.py", line 1006, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.RESOURCE_EXHAUSTED
        details = "CLIENT: Received message larger than max (147378060 vs. 4194304)"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:2379 {created_time:"2025-02-27T17:17:55.590196888-05:00", grpc_status:8, grpc_message:"CLIENT: Received message larger than max (147378060 vs. 4194304)"}"
>
>>>
```
