### ISSUE TITLE
etcd3.exceptions.ConnectionFailedError

### ISSUE THREAD

**Issue by surinkim** [kragniz/python-etcd3#419]
My python code is simple from [etcd3 readme.md](https://github.com/kragniz/python-etcd3).

    import etcd3
    etcd = etcd3.client()
    etcd.get('foo')

However, when the script run, `etcd3.exceptions.ConnectionFailedError
` has occurred.

Because I can it by using `curl + etcdctl`, so, I think it is not `etcd` problem.

    $ curl -L http://localhost:4001/v2/keys/mykey -XPUT -d value="Hello"
    {"action":"set","node":{"key":"/mykey","value":"Hello","modifiedIndex":52,"createdIndex":52},"prevNode":{"key":"/mykey","value":"Hello World","modifiedIndex":51,"createdIndex":51}}
    $ 
    $ etcdctl get /mykey
    Hello

**Is it etcd3's bug? How can I solve this problem?**

I'm currently using `etcd3 0.7.0`.
I've tried even the old version(0.4.0 ~ 0.6.0), but I still have problems.

My stack trace is below,

    (scaling_python_kor) hyun@hyun-VirtualBox:~/work/scaling_python_kor/Chapter07$ python 08_etcd-lock.py 
    Traceback (most recent call last):
      File "/home/hyun/work/scaling_python_kor/lib/python3.5/site-packages/etcd3/client.py", line 46, in handler
        return f(*args, **kwargs)
      File "/home/hyun/work/scaling_python_kor/lib/python3.5/site-packages/etcd3/client.py", line 249, in get
        credentials=self.call_credentials,
      File "/home/hyun/work/scaling_python_kor/lib/python3.5/site-packages/grpc/_channel.py", line 487, in __call__
        return _end_unary_response_blocking(state, call, False, deadline)
      File "/home/hyun/work/scaling_python_kor/lib/python3.5/site-packages/grpc/_channel.py", line 437, in _end_unary_response_blocking
        raise _Rendezvous(state, None, None, deadline)
    grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Trying to connect an http1.x server)>
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "08_etcd-lock.py", line 5, in <module>
        etcd.get('foo')
      File "/home/hyun/work/scaling_python_kor/lib/python3.5/site-packages/etcd3/client.py", line 48, in handler
        _translate_exception(exc)
      File "/home/hyun/work/scaling_python_kor/lib/python3.5/site-packages/etcd3/client.py", line 32, in _translate_exception
        raise exception
    etcd3.exceptions.ConnectionFailedError

**Comment by surinkim** [comment]
I did not check the version of etcd in advance. 
After installing etcd version 3.3.4, everything is OK.
The version I installed was 2.2.5.
