### ISSUE TITLE
Wrap grpc exceptions

### ISSUE THREAD

**Issue by takac** [kragniz/python-etcd3#72]
The client can throw out quite confusing grpc exceptions which could be neatly wrapped.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  ...
  File "/usr/local/lib/python3.5/site-packages/etcd3/client.py", line 525, in add_member
    self.timeout)
  File "/usr/local/lib/python3.5/site-packages/grpc/_channel.py", line 481, in __call__
    return _end_unary_response_blocking(state, False, deadline)
  File "/usr/local/lib/python3.5/site-packages/grpc/_channel.py", line 432, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
```

Deadline exceeded is a non critical error I would like to catch:

```python
for i in range(4):
    try:
        etcd.add_member(["http://172.1.1.1:2380"])
        return True   
    except DeadlineExceeded:
        print("hit deadline")
     return False
```

Another obvious one I have seen: StatusUnavailable

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/etcd3/client.py", line 564, in members
    self.timeout)
  File "/usr/local/lib/python3.5/site-packages/grpc/_channel.py", line 481, in __call__
    return _end_unary_response_blocking(state, False, deadline)
  File "/usr/local/lib/python3.5/site-packages/grpc/_channel.py", line 432, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, )>
```

**Comment by kragniz** [comment]
Should be fixed with #63
