### ISSUE TITLE
Install errors on 0.11.0

### ISSUE THREAD

**Issue by RattyDAVE** [kragniz/python-etcd3#952]
In the past hour or so I am now getting errors. I think this may be related to the new commit.

Output below.

DAVE

```
# pip install etcd3
Collecting etcd3
  Using cached https://files.pythonhosted.org/packages/a6/99/c3ae7544f75067192c490f817b9440acbe32dda1f7e9c27b19c1e85c46e3/etcd3-0.11.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /opt/tljh/hub/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-eyzmdsdq/etcd3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-eyzmdsdq/etcd3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-eyzmdsdq/etcd3/pip-egg-info
         cwd: /tmp/pip-install-eyzmdsdq/etcd3/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-eyzmdsdq/etcd3/setup.py", line 23, in <module>
        requirements = load_reqs('requirements/base.txt')
      File "/tmp/pip-install-eyzmdsdq/etcd3/setup.py", line 16, in load_reqs
        with open(filename) as reqs_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements/base.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by RattyDAVE** [comment]
Just doing some diags and 'pip install etcd3==0.10.0' works fine.
